refactor code
Ntare22/calc-react-ii pull request #4
Opened 2021-12-02 21:52 UTC by Ntare22

refactor calculator and App to functional components to use hooks

2021-12-02 23:36 UTC, D4nielJ requested changes
## Hello @Ntare22, 

You're doing great! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights :fire: :rocket: 
- Your application works correctly after the refactor of main components!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

## Happy coding and stay awesome! 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-02 23:36 UTC, D4nielJ commented on src/App.js
> +      <Calculator handleClick={clickHandler} calcState={stateOfCalc} />
[OPTIONAL] I think you don't need to deconstruct the object here, to construct a new object to pass on props. You could just pass the state in `calcState={state}` and save a couple of lines. :sweat_smile:

2021-12-02 23:36 UTC, D4nielJ commented on src/components/Calculator.js
> +      <NumsOperations handleClick={handleClick} />
- [ ] Let's change NumsOperations to work as a stateless functional component as the requirement of this project is to refactor all components.

2021-12-03 15:31 UTC, AshakaE approved these changes
### Hi @Ntare22   🙋‍♀️, 

# STATUS APPROVED ✔

Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 15:40 UTC, Ntare22 commented
> ### Hi @Ntare22 🙋‍♀️,
> # STATUS APPROVED ✔
> Your project is complete! There is nothing else to say other than... it's time to merge it 🔗 🚢 Congratulations! 🎉
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers 🥂 and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hey..

Thanks for the approval. Can you change the status on the platform, so that I'm able to submit the final project.

2021-12-03 20:49 UTC, merged